### ISSUE TITLE
Add support for positional arguments

### ISSUE THREAD

**Issue by dgrine** [dgrine/Argo#4]
Support these type of invocations:

```
ld -o <output> <objfile> <...>
```

**Comment by phforest** [comment]
beware , with this option : 
suddenly other options became unkown.
```
./wow -o russian-entity.sqlite  bank.wow --verbose trace
Error: Unknown option '--verbose'
```
but this works:
```./wow -o russian-entity.sqlite  --verbose trace bank.wow```

**Comment by dgrine** [comment]
The library currently tries to follow Python's argparse behavior. There, all `-` or `--` options must come before positional options.

However, you're right: it would be more flexible to remove this restriction!
